spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: ThanhPhong1507
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

authentication:
  configs:
    accessTokenSecret: "T,|frpoBfvnZVdFsEWI7OOSGQYa[Xd}pR*TTJnSpn/xLpvNTOirBOG9gE7fR0kRjEdh6W*FpQSbOUdUGabpwhitV]EjTr4NiU*QMiRC+H606osH-j8SNfE5E+c.2ikz4ul}syhD7GN[eLxLaa|*Ey9qp1txe//2aSs8VuTAPoCU,9F6+.Ur|RtOimcVb9js1coBz96Nkx[MxG8y[*Ss{DPmYK1ZcjwjvhTo46Gx|jFrp.HjAJi{i}+0oCrLW]TDZ"
    access-token-expiration-minutes: 120
    refreshTokenExpirationMinutes: 131400
    refreshTokenSecret: "B2]r}y{Vxn2G{pv3|XrLC|nzdV4DnqwOQ,4C]{jcYfj[{UW,u8V8Hxw+Wn}JBlPqLUxZic8SdQmiiZyS2Z][VGj2LO{ISun4YQ,GV}|nl{M1aY[2[3k]4wh4IVgzJVHx}v0+0T[MRBv/2fhZWAgGSoHmo-}by57vW-.,K[hcPADKv4m/yWlsJiHmSoqPv}-Ac76gMpRefPkNOr-qidZ.E{GD||aDeP[LoBc1axpLt5G6|Rry{h80qlh7*T9R3fG|"
    issuer: "http://localhost:8080"
    audience: "http://localhost:8080"

openapi:
  service:
    title: "phong api"
    version: "1.0.0"
    server: "http://localhost:8080"
    group: "PHONG ECOMMERCE API"

logging:
  level:
    net:
      ttddyy:
        dsproxy:
          listener: DEBUG
